MovieRider/Controllers/Api/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieRider.Data;
using MovieRider.Dtos;
using MovieRider.Models;

namespace MovieRider.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class CustomersController : ControllerBase
    {
        private ApplicationDbContext _context;
        private IMapper _mapper;

        
        public CustomersController(ApplicationDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        //GET /api/customers
        public IActionResult GetCustomers(string query = null)
        {
            var customersQuery = _context.Customers.Include(c => c.MembershipType).ToList();

            if (!String.IsNullOrWhiteSpace(query))
            {
                customersQuery = customersQuery.Where(c => c.Name.Contains(query)).ToList();
            }
            var customerDtos = customersQuery.Select(_mapper.Map<Customer, CustomerDto>);
            
            /*var customerDtos = _context.Customers.Include(c => c.MembershipType).ToList().Select(_mapper.Map<Customer, CustomerDto>);*/

            return Ok(customerDtos);
        }

        //GET /api/customers/1
        [HttpGet("{id}")]
        public IActionResult GetCustomer(int id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == id);

            if (customer == null)
                return NotFound();

            return Ok(_mapper.Map<Customer,CustomerDto>(customer));
        }

        // POST /api/customers
        // To add "NotFound()" or NotFoundResult() should be a IActionResult CreateCustomer
        [HttpPost]
        [Authorize(Roles=RoleName.CanManageMovies)]
        public IActionResult CreateCustomer(CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var customer = _mapper.Map<CustomerDto, Customer>(customerDto);
            _context.Customers.Add(customer);
            _context.SaveChanges();

            customerDto.Id = customer.Id;

            return Created(new Uri(UriHelper.GetDisplayUrl(Request)+"/"+customer.Id), customerDto); 

        }

        // PUT /api/customers/1
        [HttpPut("{id}")]
        [Authorize(Roles = RoleName.CanManageMovies)]
        public void UpdateCustomer(int id, CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
                throw new Exception("Bad request");

            var customerInDb = _context.Customers.SingleOrDefault(c => c.Id == id);

            if (customerInDb == null) 
                throw new Exception("Not Found");

            _mapper.Map(customerDto,customerInDb);

            /*
            customerInDb.FirstName = customerDto.FirstName;
            customerInDb.LastName = customerDto.LastName;
            customerInDb.BirthDate = customerDto.BirthDate;
            customerInDb.IsSubscibedToNewsLetter = customerDto.IsSubscibedToNewsLetter;
            customerInDb.MembershipTypeId = customerDto.MembershipTypeId;
            */

            _context.SaveChanges();
        }

        // DELETE /api/customer/1
        [HttpDelete("{id}")]
        [Authorize(Roles = RoleName.CanManageMovies)]
        public void DeleteCustomer(int id)
        {
            var customerInDb = _context.Customers.SingleOrDefault(c => c.Id == id);

            if (customerInDb == null)
                throw new Exception("Not Found");
           
            _context.Customers.Remove(customerInDb);
            _context.SaveChanges();
        }

    }
}

MovieRider/Controllers/Api/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieRider.Data;
using MovieRider.Dtos;
using MovieRider.Models;

namespace MovieRider.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class MoviesController : ControllerBase
    {
        private ApplicationDbContext _context;
        private IMapper _mapper;
        public MoviesController(ApplicationDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        // GET /api/movies
        public IEnumerable<MovieDto> GetMovies(string query = null)
        {

            var moviesQuery = _context.Movies
                .Include(m => m.Genre)
                .Where(m => m.NumberAvailable > 0);

            if (!String.IsNullOrWhiteSpace(query))
            {
                moviesQuery = moviesQuery.Where(m => m.Name.Contains(query));
            }

            return moviesQuery
                .ToList()
                .Select(_mapper.Map<Movie, MovieDto>);
        }

        // GET /api/movies/1
        [HttpGet("{id}")]
        public IActionResult GetCustomer(int id)
        {
            var movie = _context.Movies.SingleOrDefault(m => m.Id == id);

            if (movie == null)
                return NotFound();

            return Ok(_mapper.Map<Movie, MovieDto>(movie));
        }

        //POST /api/movies
        [HttpPost]
        [Authorize(Roles = RoleName.CanManageMovies)]
        public IActionResult CreateMovie(MovieDto movieDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var movie = _mapper.Map<MovieDto, Movie>(movieDto);
            _context.Movies.Add(movie);
            _context.SaveChanges();

            movieDto.Id = movie.Id;

            return Created(new Uri(UriHelper.GetDisplayUrl(Request) + "/" + movie.Id), movieDto);
        }

        //PUT /api/movies/1
        [HttpPut("{id}")]
        [Authorize(Roles = RoleName.CanManageMovies)]
        public void UpdateMovie(int id, MovieDto movieDto)
        {
            if (!ModelState.IsValid)
                throw new Exception("Bad request");

            var movieInDb = _context.Movies.SingleOrDefault(m => m.Id == id);

            if (movieInDb == null)
                throw new Exception("Not Found");

            _mapper.Map(movieDto, movieInDb);

            _context.SaveChanges();
        }

        //DELETE /api/movies/1
        [HttpDelete("{id}")]
        [Authorize(Roles = RoleName.CanManageMovies)]
        public void DeteleMovie(int id)
        {
            var movieInDb = _context.Movies.SingleOrDefault(m => m.Id == id);

            if (movieInDb == null)
                throw new Exception("Not Found");

            _context.Movies.Remove(movieInDb);

            _context.SaveChanges();
        }
    }
}

MovieRider/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MovieRider.Controllers
{
    public class RentalsController : Controller
    {
        public IActionResult New()
        {
            return View();
        }
    }
}

MovieRider/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieRider</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/jquery/datatables/css/dataTables.bootstrap.css" />
        <link rel="stylesheet" href="~/css/site-theme.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/toastr/toastr.css" />
        <link rel="stylesheet" href="~/lib/toastr/toastr.js.map" />
        <link rel="stylesheet" href="~/lib/jquery/datatables/css/responsive.bootstrap.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site-theme.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css"
              asp-fallback-href="~/lib/jquery/datatables/css/dataTables.bootstrap.min.css" />
        <link rel="stylesheet" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" asp-fallback-href="~/lib/toastr/toastr.css" />
        <link rel="stylesheet" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.js.map" asp-fallback-href="~/lib/toastr/toastr.js.map" />
        <link rel="stylesheet" src="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap.min.css" asp-fallback-href="~/lib/jquery/datatables/css/responsive.bootstrap.min.css" />
    </environment>
</head>
<body>
    <partial name="_Navbar" />
    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Movie Rider</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootbox.js" asp-append-version="true"></script>
        <script src="~/lib/jquery/datatables/js/dataTables.bootstrap.js" asp-append-version="true"></script>
        <script src="~/lib/jquery/datatables/js/jquery.dataTables.js" asp-append-version="true"></script>
        <script src="~/lib/typeahead/typeahead.bundle.js" asp-append-version="true"></script>
        <script src="~/lib/jquery/datatables/js/dataTables.responsive.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery/datatables/js/responsive.bootstrap.min.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"
                asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.9/jquery.validate.unobtrusive.min.js" asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js" asp-fallback-src="~/lib/bootbox.min.js" asp-append-version="true"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js" asp-fallback-src="~/lib/jquery/datatables/js/dataTables.bootstrap.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" asp-fallback-src="~/lib/jquery/datatables/js/jquery.dataTables.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/corejs-typeahead/1.2.1/typeahead.bundle.min.js" asp-fallback-src="~/lib/typeahead/typeahead.bundle.min.js"></script>
        <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js" asp-fallback-src="~/lib/jquery/datatables/js/dataTables.responsive.min.js"></script>
        <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap.min.js" asp-fallback-src="~/lib/jquery/datatables/js/responsive.bootstrap.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

MovieRider/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand nav-menu-brand">Movie rider</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav nav-menu">
                <li><a asp-area="" asp-controller="Rentals" asp-action="New">New rental</a></li>
                <li><a asp-area="" asp-controller="Customers" asp-action="Index">Customers</a></li>
                <li><a asp-area="" asp-controller="Movies" asp-action="Index">Movies</a></li>
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>